### ISSUE TITLE
Command line usage

### ISSUE THREAD

**Issue by smith6jt-cop** [murphygroup/CellSegmentationEvaluator#1]
For anyone else having difficulty running the example data on WSL2 Ubuntu python 3.8, instead of using this from the README:

python seg_eval_main.py --img-dir [example_data/imgs/2D_CODEX.ome.tiff] --mask-dir [example_data/masks/2D_CODEX.ome.tiff]

Use this:

python seg_eval_main.py example_data/imgs/2D_CODEX.ome.tiff example_data/masks/2D_CODEX.ome.tiff

**Comment by rfmurphy** [comment]
Posting a corrected README.
